server:
  port: 39999

spring:
  kafka:
    template:
      default-topic: jr.cloud.practice.v1
    bootstrap-servers: localhost:9092
    properties:
      schema:
        registry:
          url: http://localhost:8081
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: inventory.management
      enable-auto-commit: false
      auto-offset-reset: earliest
      properties:
        specific.avro.reader: true
        isolation.level: read_committed